"""4 migration

Revision ID: 2a941935db72
Revises: 05ab81ac0770
Create Date: 2023-11-23 19:20:25.146686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a941935db72'
down_revision: Union[str, None] = '05ab81ac0770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'student_id')
    # ### end Alembic commands ###
