"""5 migration

Revision ID: bd8783bc1bfb
Revises: 2a941935db72
Create Date: 2023-11-23 19:21:19.022909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8783bc1bfb'
down_revision: Union[str, None] = '2a941935db72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'course_id')
    # ### end Alembic commands ###
